# Generated by Django 4.0.5 on 2022-08-01 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='passive',
            field=models.TextField(blank=True, verbose_name='Пассивная способность'),
        ),
        migrations.AddField(
            model_name='artifact',
            name='star',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Редкость'),
        ),
        migrations.AddField(
            model_name='character',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='character',
            name='star',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Редкость'),
        ),
        migrations.AddField(
            model_name='typeartifact',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='typeweapon',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='awakening',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Пробуждение'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Уровень'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='passive',
            field=models.TextField(blank=True, verbose_name='Пассивная способность'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='star',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Редкость'),
        ),
    ]
