# Generated by Django 4.0.5 on 2022-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0002_artifact_level_artifact_name_artifact_passive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifact',
            options={'verbose_name': 'Артефакт', 'verbose_name_plural': 'Артефакты'},
        ),
        migrations.AlterModelOptions(
            name='character',
            options={'verbose_name': 'Персонаж', 'verbose_name_plural': 'Персонажи'},
        ),
        migrations.AlterModelOptions(
            name='characterbuild',
            options={'verbose_name': 'Билд', 'verbose_name_plural': 'Билды'},
        ),
        migrations.AlterModelOptions(
            name='typeartifact',
            options={'verbose_name': 'Тип артефакта', 'verbose_name_plural': 'Типы артефактов'},
        ),
        migrations.AlterModelOptions(
            name='typeweapon',
            options={'verbose_name': 'Тип оружия', 'verbose_name_plural': 'Типы оружия'},
        ),
        migrations.AlterModelOptions(
            name='weapon',
            options={'verbose_name': 'Оружие', 'verbose_name_plural': 'Оружие'},
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='name',
            field=models.CharField(default=' ', max_length=255, verbose_name='Название'),
        ),
    ]
