# Generated by Django 4.0.5 on 2022-08-17 12:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0004_remove_artifact_passive'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Уровень')),
            ],
            options={
                'verbose_name': 'Артефакт',
                'verbose_name_plural': 'Артефакты',
            },
        ),
        migrations.RemoveField(
            model_name='artifact',
            name='level',
        ),
        migrations.RemoveField(
            model_name='characterbuild',
            name='artifacts',
        ),
        migrations.RemoveField(
            model_name='characterbuild',
            name='name',
        ),
        migrations.RemoveField(
            model_name='characterbuild',
            name='weapon',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='awakening',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='level',
        ),
        migrations.AddField(
            model_name='characterbuild',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Уровень'),
        ),
        migrations.CreateModel(
            name='WeaponBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awakening', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Пробуждение')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(90)], verbose_name='Уровень')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.weapon', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'Оружие',
                'verbose_name_plural': 'Оружие',
            },
        ),
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameBuild', models.CharField(default='Сборка № ', max_length=255, verbose_name='Название')),
                ('artifacts', models.ManyToManyField(to='constructor.artifactbuild', verbose_name='Артефакты')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.characterbuild', verbose_name='Персонаж')),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructor.weaponbuild', verbose_name='Оружие')),
            ],
            options={
                'verbose_name': 'Билд',
                'verbose_name_plural': 'Билды',
            },
        ),
        migrations.AddField(
            model_name='artifactbuild',
            name='artifact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='constructor.artifact', verbose_name='Артефакт'),
        ),
    ]
