# Generated by Django 4.0.5 on 2022-08-19 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0006_element_alter_artifactbuild_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'verbose_name': 'Стихия', 'verbose_name_plural': 'Стихии'},
        ),
        migrations.AddField(
            model_name='element',
            name='slug',
            field=models.SlugField(default=' ', max_length=10),
        ),
    ]
