# Generated by Django 4.0.5 on 2022-08-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0007_alter_element_options_element_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='artifact',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/artifact/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='build',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/build/<django.db.models.fields.CharField>', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='character',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/character/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='element',
            name='img_background',
            field=models.ImageField(blank=True, upload_to='images/element/background/', verbose_name='Фон карточки'),
        ),
        migrations.AddField(
            model_name='typeartifact',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/type/artifact', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='typeweapon',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/type/weapon', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='img',
            field=models.ImageField(blank=True, help_text='.png, то есть без фона', upload_to='images/weapon/', verbose_name='Изображение'),
        ),
    ]
