# Generated by Django 4.0.5 on 2022-08-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructor', '0008_artifact_img_build_img_character_img_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='img_background',
        ),
        migrations.AddField(
            model_name='element',
            name='color',
            field=models.CharField(default='000000', max_length=8, verbose_name='Цвет фона'),
        ),
    ]
